# Generated by Buildr 1.4.6, change to your liking

require 'rubygems'
require 'buildr/jetty'
require 'readline'
require 'fileutils'

# Setup
def tmp_dir
    File.join(File.dirname(__FILE__), "tmp")
end

#rm_rf tmp_dir
FileUtils::mkdir_p tmp_dir

ENV['JAVA_OPTS'] = "-Djava.io.tmpdir=#{tmp_dir} -Dfile.encoding=UTF-8"

repositories.remote << "http://repository.springsource.com/maven/bundles/release/"
repositories.remote << "http://repository.springsource.com/maven/bundles/external/"
repositories.remote << 'http://www.ibiblio.org/maven2'
repositories.remote << 'http://download.java.net/maven/2'
repositories.remote << 'http://repo1.maven.org/maven2'
repositories.remote << 'https://repository.jboss.org/nexus/content/groups/public-jboss'
repositories.remote << 'https://repository.jboss.org/nexus/content/groups/public-jboss'

# Spring
SPRING_VERSION = '3.0.5.RELEASE'
SPRING = struct(
    :core => group('spring-beans', 'spring-context', :under=>"org.springframework", :version=>SPRING_VERSION),
    :jdbc => transitive("org.springframework:spring-jdbc:jar:#{SPRING_VERSION}"),
    :mvc => transitive("org.springframework:spring-webmvc:jar:#{SPRING_VERSION}"),
    :test => "org.springframework:spring-test:jar:#{SPRING_VERSION}"
)


# Jetty
JETTY_JSP = group('jsp-api-2.1', 'jsp-2.1', :under=> 'org.mortbay.jetty', :version=> Buildr::Jetty::VERSION)

# Dependency

GUAVA = 'com.google.guava:guava:jar:r09'

SLF4J_VERISON = "1.5.6"
SLF4J = struct(
    :api => "org.slf4j:slf4j-api:jar:#{SLF4J_VERISON}",
    :runtime => transitive("org.slf4j:slf4j-log4j12:jar:#{SLF4J_VERISON}")
)

BASIC_DEPENDENCY = struct(
    :guava => GUAVA,
    :log => SLF4J.api
)
RUNTIME_DEPENDENCY = [SLF4J.runtime]

MOCKITO = 'org.mockito:mockito-all:jar:1.8.5'

TEST_DEPENDENCY = struct(
    :mock => MOCKITO,
    :spring => SPRING.test
)

# Cache
EH_CACHE_VERSION = "2.4.2"
EH_CACHE = "net.sf.ehcache:ehcache-core:jar:#{EH_CACHE_VERSION}"

# FreeMarker
FREEMARKER = 'org.freemarker:freemarker:jar:2.3.18'

# Project
desc "The mvcdemo project"
define "mvcdemo" do
	project.version = "1.0.0"
	project.group = "com.fssle.mvcdemo"
	compile.options.target = '1.5'
	
	task :build => [:clean]

	define "web" do
		WEB_DEPENDENCY = struct(
			:basic => BASIC_DEPENDENCY,
			:mvc => SPRING.mvc,
			:view => FREEMARKER,
			:cache => EH_CACHE
		)

		WEB_PACKAGE_DEPENDENCY = struct(
			:web => WEB_DEPENDENCY,
			:runtime => RUNTIME_DEPENDENCY
		)

		WEB_TEST_DEPENDNCY = struct(
			:test => TEST_DEPENDENCY,
			:runtime => RUNTIME_DEPENDENCY
		)

		compile.with WEB_DEPENDENCY
		package(:war).with :libs=> WEB_PACKAGE_DEPENDENCY
		test.with WEB_TEST_DEPENDNCY

		Java.classpath << JETTY_JSP

		task("jetty"=>[package(:war), jetty.use]) do |task|
			jetty.deploy("http://localhost:8080", task.prerequisites.first)
			Readline::readline('[Type ENTER to stop Jetty]')
		end
  	end

end